baseURL = "https://virtualsach.github.io/"
languageCode = "en-us"
title = "Virtual Sachin"


[params]
  description = "Cloud Architect | Automation Expert | Infrastructure Strategy"
  author = "Sachin"
