baseURL = "https://virtualsach.in/"
languageCode = "en-us"
title = "Virtual Sachin"


[params]
  description = "Cloud Architect | Automation Expert | Infrastructure Strategy"
  author = "Sachin"

  [params.social]
    github = "https://github.com/virtualsach"
    linkedin = "https://www.linkedin.com/in/sachin-sharma-711/"
    email = "mailto:sachin@virtualsach.in"

[menus]
  [[menus.main]]
    name = "About"
    url = "/about"
    weight = 10
  [[menus.main]]
    name = "Projects"
    url = "/projects"
    weight = 20
  [[menus.main]]
    name = "Insights"
    url = "/posts"
    weight = 30
  [[menus.main]]
    name = "Let's Talk"
    url = "/contact"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

